### ISSUE TITLE
Access requested URL in interceptor

### ISSUE THREAD

**Issue by norbertpy** [allfro/pymiproxy#8]
Thanks for this cool little lib. Is there a way to access the requested URL inside the interceptor? My use case is, I want to add an HTTP header whenever the URL matches a specific pattern.

```python
class DebugInterceptor(RequestInterceptorPlugin, ResponseInterceptorPlugin):

    def do_request(self, data):
        # access request url and do a regex
        return data

    def do_response(self, data):
        return data
```

**Comment by allfro** [comment]
Hi Norbert,

That's a good point and I haven't thought of that when designing these
classes. You could do it with a bit of work by overriding the
mitm_request/response methods since they belong to ProxyHandler which is a
subclass of python's HttpBaseRequestHandler. This would give you access to
the following fields: self.is_connect (True if SSL), self.path (/blah), and
self.hostname (Google.com). Using those three fields you could create a
URL. There is one limitation in that you would only be able to write one
interceptor that way. However, what you could do is write a completely
different interceptor class and reuse the original code from the mitm_*
methods to pass in a URL. Does that make sense?

Cheers

Nadeem

**Comment by norbertpy** [comment]
Thanks Nadeem. I'll give it a shot.
